# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170723_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='author_id',
        ),
    ]
