# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170723_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='book_id',
            field=models.ManyToManyField(to='books.Books'),
        ),
        migrations.RemoveField(
            model_name='books',
            name='author_id',
        ),
        migrations.AddField(
            model_name='books',
            name='author_id',
            field=models.ManyToManyField(to='books.Authors'),
        ),
    ]
