# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:01
from __future__ import unicode_literals

import apps.loginregistration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[apps.loginregistration.models.validateLength])),
                ('last_name', models.CharField(max_length=25, validators=[apps.loginregistration.models.validateLength])),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25, validators=[apps.loginregistration.models.validatePasswd])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
