# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:01
from __future__ import unicode_literals

import apps.loginregistration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=25, validators=[apps.loginregistration.models.validatePasswd, apps.loginregistration.models.validateEmail]),
        ),
    ]
