# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.ManyToManyField(to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.ManyToManyField(to='products.Store'),
        ),
    ]
