# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170725_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description_id',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='description',
            name='course_id',
        ),
    ]
