# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('published_date', models.DateTimeField()),
                ('in_print', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_id', models.ManyToManyField(to='fullstackbooks.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_id', models.ManyToManyField(to='fullstackbooks.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.ManyToManyField(to='fullstackbooks.Category'),
        ),
        migrations.AddField(
            model_name='author',
            name='book_id',
            field=models.ManyToManyField(to='fullstackbooks.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='category_id',
            field=models.ManyToManyField(to='fullstackbooks.Category'),
        ),
    ]
