# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstackbooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category_id',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='none', max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='none', max_length=16),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
