# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullstackbooks', '0002_auto_20170725_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
